---
# weareinteractive.users
users:
  - username: "{{ vault_username }}"
    password: "{{ lookup('env', 'MKPASSWD_USER') }}"
    shell: /bin/bash
    users_group: "{{ vault_username }}"
    authorized_keys:
      - "{{ lookup('file', '{{ my_home }}/.ssh/id_rsa.pub') }}"
      - "{{ lookup('file', '{{ my_home }}/.ssh/id_rsa2022.pub') }}"

# grog.package
package_list:
  - name: curl
  - name: git
  - name: htop
  - name: iftop
  - name: iotop
  - name: lm-sensors
  - name: mc
  - name: ncdu
  - name: net-tools
  - name: nmap
  - name: openssh-server
  - name: python
  - name: qemu-guest-agent
  - name: screen
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget

# geerlingguy.ntp
ntp_timezone: "America/Detroit"

# geerlingguy.security
security_ssh_port: 22
security_ssh_password_authentication: "yes"
security_ssh_permit_root_login: "yes"
security_ssh_usedns: "no"
security_autoupdate_enabled: true
security_fail2ban_enabled: false
security_sudoers_passwordless:
  - "{{ vault_username }}"

# ironicbadger.docker_compose_generator
appdata_path: /opt/appdata
global_env_vars:
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: "/home/{{ vault_username }}"
