---
ansible_python_interpreter: auto_silent
ansible_user: ansible
ansible_ssh_private_key_file: ~/.ssh/ansible_ed25519

# users role
users_list:
  - username: "{{ lookup('env', 'SSH_USER') }}"
    password: >-
      {{ lookup('env', 'SSH_USER_PASS') | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}
    shell: /bin/bash
    users_group: "{{ lookup('env', 'SSH_USER') }}"
    authorized_keys:
      - "{{ lookup('env', 'SSH_PUBLIC_KEY') }}"

# packages role
package_list:
  - name: curl
  - name: git
  - name: htop
  - name: iftop
  - name: iotop
  - name: lm-sensors
  - name: mc
  - name: ncdu
  - name: net-tools
  - name: nmap
  - name: openssh-server
  - name: python3
  - name: qemu-guest-agent
  - name: screen
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget

# unifi role
unifi_dhcp_reservations:
  - name: ansalon
    mac: "6c:1f:f7:76:99:8f"
    ip: "192.168.233.6"
  - name: kaz
    mac: "bc:24:11:10:00:01"
    ip: "192.168.233.10"
  - name: jetkvm
    mac: "44:b7:d0:e7:82:89"
    ip: "192.168.233.11"
  - name: printer
    mac: "54:35:30:68:19:38"
    ip: "192.168.233.15"
  - name: tailscale
    mac: "ea:31:e7:19:05:63"
    ip: "192.168.233.21"
  - name: drizzt
    mac: "6c:6e:07:1e:39:74"
    ip: "192.168.233.27"
  - name: magius
    mac: "d0:37:45:cf:ce:4c"
    ip: "192.168.233.29"
  - name: kaladin
    mac: "c4:35:d9:89:4c:b4"
    ip: "192.168.233.30"
  - name: kvothe
    mac: "54:bf:64:2e:b2:51"
    ip: "192.168.233.31"
  - name: homeassistant
    mac: "b8:27:eb:75:3a:e3"
    ip: "192.168.233.35"
  - name: coltons-tablet
    mac: "da:4d:62:21:d6:88"
    ip: "192.168.233.240"
  - name: solinari
    mac: "00:11:32:8e:27:e1"
    ip: "192.168.233.200"
  - name: minecraft
    mac: "bc:24:11:13:00:01"
    ip: "192.168.233.19"

unifi_port_forwards:
  - name: minecraft
    proto: udp
    dst_port: "19132"
    fwd: "192.168.233.19"
    fwd_port: "19132"
    enabled: true

# geerlingguy.ntp
ntp_timezone: "America/Detroit"

# geerlingguy.security
security_ssh_port: 22
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_autoupdate_enabled: true
security_fail2ban_enabled: false
security_sudoers_passwordless:
  - "{{ lookup('env', 'SSH_USER') }}"
