---
# weareinteractive.users
users:
  - username: "{{ vault_username }}"
    password: "{{ lookup('env', 'MKPASSWD_USER') }}"
    shell: /bin/bash
    users_group: "{{ vault_username }}"
    authorized_keys:
      - "{{ lookup('file', '/home/{{ vault_username }}/.ssh/id_rsa.pub') }}"
      - "{{ lookup('file', '/home/{{ vault_username }}/.ssh/id_rsa2022.pub') }}"

# grog.package
package_list:
  - name: curl
  - name: git
  - name: htop
  - name: iftop
  - name: iotop
  - name: lm-sensors
  - name: mc
  - name: ncdu
  - name: net-tools
  - name: nmap
  - name: openssh-server
  - name: python
  - name: qemu-guest-agent
  - name: screen
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget

# geerlingguy.ntp
ntp_timezone: "America/Detroit"
