---
# weareinteractive.users
users:
  - username: "{{ vault_username }}"
    password: "{{ lookup('env', 'MKPASSWD_USER') }}"
    shell: /bin/bash
    users_group: "{{ vault_username }}"
    authorized_keys:
      - "{{ lookup('file', '{{ my_home }}/.ssh/id_rsa.pub') }}"
      - "{{ lookup('file', '{{ my_home }}/.ssh/id_rsa2022.pub') }}"

# grog.package
package_list:
  - name: curl
  - name: git
  - name: htop
  - name: iftop
  - name: iotop
  - name: lm-sensors
  - name: mc
  - name: ncdu
  - name: net-tools
  - name: nmap
  - name: openssh-server
  - name: python
  - name: qemu-guest-agent
  - name: screen
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget

# geerlingguy.ntp
ntp_timezone: "America/Detroit"

# ironicbadger.docker_compose_generator
appdata_path: /opt/appdata
global_env_vars:
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: "/home/{{ vault_username }}"
