---
# tasks file for truenas

- name: Configure TrueNAS iSCSI
  ansible.builtin.include_tasks: iscsi.yml

- name: Create LVM VG on iSCSI LUN
  ansible.builtin.include_tasks: iscsi_lvm.yml

- name: Configure NFS shares
  ansible.builtin.include_tasks: nfs.yml
