---
fail_fast: false
minimum_pre_commit_version: "4.1.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
        files: ^scripts/
      - id: check-json
        exclude: ^\.devcontainer/devcontainer\.json$
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: \.(tf|tfvars)$ # Let terraform_fmt handle these
      - id: trailing-whitespace
        exclude: \.(tf|tfvars)$ # Let terraform_fmt handle these

  # Fast checks for every commit
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_tflint
        files: ^terraform/.*\.tf$
        args:
          - --args=--config=__GIT_WORKING_DIR__/terraform/.tflint.hcl
          - --args=--recursive
          - --args=--fix
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
        stages: [pre-commit]
      - id: terraform_fmt
        stages: [pre-commit]
      - id: terraform_validate
        args:
          - --hook-config=--retry-once-with-cleanup=true
        stages: [pre-commit]

  - repo: https://github.com/ansible/ansible-lint
    rev: v26.1.1
    hooks:
      - id: ansible-lint
        args:
          - --fix
        stages: [pre-commit]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        args:
          - --fix
        files: \.(md|markdown)$
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: check-ansible-vault
        name: Check Ansible Vault Encryption
        entry: |
          bash -c 'for file in "$@"; do
            if ! grep -q "\$ANSIBLE_VAULT;" "$file"; then
              echo "ERROR: $file is not encrypted! Run \"task encrypt\" and try again."
              exit 1
            fi
          done' --
        language: system
        files: ^(vars/vault\.yml|envrc)$
        pass_filenames: true
        stages: [pre-push]
