---
- hosts: huma
  vars_files:
    - vars/vault.yml
  roles:
    - role: grog.package
    - role: ironicbadger.proxmox_nag_removal
    - role: weareinteractive.users
#     - role: weareinteractive.users
#     - role: weareinteractive.environment
#     - role: geerlingguy.ntp
#     - role: geerlingguy.security
#     - role: geerlingguy.docker
#     - role: geerlingguy.pip
#     - role: oefenweb.nfs_client
#     - role: network
#     - role: artis3n.tailscale
# #  geerlingguy.github-users
#  rossmcdonald.telegraf
#  shelleg.ansible_role_portainer

- hosts: unifi
  vars_files:
    - vars/vault.yml
  roles:
    - role: geerlingguy.ntp
    - role: grog.package
    - role: unifi_controller
    - role: weareinteractive.users

- hosts: tailscale
  vars_files:
    - vars/vault.yml
  roles:
    - role: geerlingguy.ntp
    - role: grog.package
    - role: artis3n.tailscale
    - role: weareinteractive.users
  tasks:
    - name: Enable IP forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        ignoreerrors: true
        sysctl_set: true

    - name: Allow IP masquerading
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        jump: MASQUERADE
