---
- name: initial setup
  hosts: all
  tasks:
    - name: linux/macos find current user home directory
      ansible.builtin.set_fact:
        my_home: "{{ lookup('env', 'HOME') }}"

- name: setup proxmox hosts
  hosts: proxmox
  vars_files:
    - vars/vault.yml
  roles:
    - role: grog.package
    - role: ironicbadger.proxmox_nag_removal
    - role: weareinteractive.users
    - role: artis3n.tailscale
    - role: install_script

- name: setup unifi server
  hosts: unifi
  vars_files:
    - vars/vault.yml
  roles:
    - role: geerlingguy.ntp
    - role: geerlingguy.security
    - role: grog.package
    - role: unifi_controller
    - role: weareinteractive.users

- name: setup tailscale server
  hosts: tailscale
  vars_files:
    - vars/vault.yml
  roles:
    - role: geerlingguy.ntp
    - role: geerlingguy.security
    - role: grog.package
    - role: artis3n.tailscale
    - role: weareinteractive.users

  tasks:
    - name: Enable IP forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        ignoreerrors: true
        sysctl_set: true

    - name: Allow IP masquerading
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        jump: MASQUERADE

- name: setup docker server
  hosts: kaz
  vars_files:
    - vars/vault.yml
  roles:
    - role: grog.package
    - role: weareinteractive.users
    - role: weareinteractive.environment
    - role: geerlingguy.ntp
    - role: geerlingguy.security
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: oefenweb.nfs_client
    - role: shelleg.ansible_role_portainer
    - role: weareinteractive.apt
