# ansible-galaxy install -r requirements.yml
---
roles:
  - src: geerlingguy.docker
    version: "8.0.0"
  - src: geerlingguy.ntp
    version: "4.0.0"
  - src: geerlingguy.security
    version: "3.0.2"

collections:
  - name: community.general
    version: "13.1.0"
  - name: ansible.posix
    version: "2.2.2"
  - name: artis3n.tailscale
    version: "1.2.1"
  - name: community.docker
    version: "5.2.1"
