# ansible-galaxy install -r requirements.yml
---
roles:
  - src: artis3n.tailscale
  - src: geerlingguy.docker
  - src: geerlingguy.github-users
  - src: geerlingguy.ntp
  - src: geerlingguy.pip
  - src: geerlingguy.security
  - src: grog.package
  - src: ironicbadger.docker_compose_generator
  - src: oefenweb.nfs_client
  - src: shelleg.ansible_role_portainer
  - src: weareinteractive.environment
  - src: weareinteractive.users

collections:
  - name: community.general
  - name: ansible.posix
