version: '3'

tasks:
  default:
    desc: Default task
    silent: true
    cmds:
      - task --list-all
      - |
        echo "------------------------------------------"
        echo "Pass args to ansible-playbook with -- args"
        echo "Example: task proxmox -- --check"
        echo "------------------------------------------"

  reqs:
    desc: Install Ansible Galaxy requirements
    cmds:
      - ansible-galaxy install -r requirements.yml

  forcereqs:
    desc: Force install Ansible Galaxy requirements
    cmds:
      - ansible-galaxy install -r requirements.yml --force

  proxmox:
    desc: Run Ansible playbook for Proxmox hosts
    cmds:
      - echo Running ansible-playbook with args {{.CLI_ARGS}}
      - ansible-playbook -b main.yml --limit proxmox --ask-pass {{.CLI_ARGS}}

  unifi:
    desc: Run Ansible playbook for Unifi hosts
    cmds:
      - ansible-playbook -b main.yml --limit unifi --ask-pass

  tailscale:
    desc: Run Ansible playbook for Tailscale hosts
    cmds:
      - ansible-playbook -b main.yml --limit tailscale --ask-pass

  plex:
    desc: Run Ansible playbook for Plex hosts
    cmds:
      - ansible-playbook -b main.yml --limit plex --ask-pass

  vault_pass:
    desc: Read vault password from 1Password
    cmds:
      - op read op://CLI/HOMELAB_VAULT_PASS/password > .vault_pass

  decrypt:
    desc: Decrypt vault files
    cmds:
      - ansible-vault decrypt vars/vault.yml
      - ansible-vault decrypt envrc --output .envrc

  encrypt:
    desc: Encrypt vault files
    cmds:
      - ansible-vault encrypt vars/vault.yml
      - ansible-vault encrypt .envrc --output envrc

  gitinit:
    desc: Initialize git hooks
    cmds:
      - ./scripts/git-init.sh
      - echo "ansible vault pre-commit hook installed"
      - echo "don't forget to create a .vault_pass"
