---
# handlers file for proxmox
- name: Restart pveproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted

- name: Update grub
  ansible.builtin.command:
    cmd: /usr/sbin/update-grub
  changed_when: true

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u
  changed_when: true

- name: Apply network config
  ansible.builtin.command:
    cmd: ifreload -a
  changed_when: true

- name: Restart multipathd
  ansible.builtin.systemd:
    name: multipathd
    state: restarted

- name: Restart pve-ha-lrm
  ansible.builtin.systemd:
    name: pve-ha-lrm
    state: restarted
  become: true

- name: Restart pve-lxc plex
  ansible.builtin.command:
    cmd: pct restart 103
  changed_when: true
