---
# handlers file for proxmox
- name: Restart pveproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted

- name: Update grub
  ansible.builtin.command:
    cmd: /usr/sbin/update-grub
  changed_when: true

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u
  changed_when: true

- name: Apply network config
  ansible.builtin.command:
    cmd: ifreload -a
  changed_when: true
