---
prometheus_version: "v3"
prometheus_port: 9090
prometheus_config_dir: /opt/prometheus/config
prometheus_data_dir: /opt/prometheus/data
prometheus_retention: 30d

grafana_version: "13.0"
grafana_port: 3000
grafana_data_dir: /opt/grafana/data
grafana_provisioning_dir: /opt/grafana/provisioning
grafana_dashboards_dir: /opt/grafana/provisioning/dashboards
grafana_admin_password: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') }}"

monitoring_network: monitoring
