---
# defaults file for pi-hole

# Upstream DNS resolvers (pi-hole will forward to these)
pihole_dns1: "1.1.1.1"
pihole_dns2: "1.0.0.1"

# Admin web interface password — pulled from Doppler
pihole_admin_password: "{{ lookup('env', 'PIHOLE_ADMIN_PASSWORD') }}"

# Pi-hole install dir
pihole_install_dir: /etc/pihole
