---
version: "3"

tasks:
  default:
    desc: Run formatting, validation, and plan
    cmds:
      - task: test

  init:
    desc: Initialize Terraform
    cmds:
      - terraform init

  test:
    desc: Format, validate, and plan Terraform changes
    cmds:
      - terraform fmt .
      - terraform validate .
      - doppler run --name-transformer tf-var -- terraform plan

  apply:
    desc: Apply Terraform changes
    cmds:
      - terraform apply -auto-approve
