---
version: "3"

tasks:
  default:
    desc: Run init, fmt, and validate
    cmds:
      - task: test

  init:
    desc: Initialize Terraform
    cmds:
      - doppler run -- sh -c 'TF_TOKEN_app_terraform_io=$TF_TOKEN_APP_TERRAFORM_IO terraform init'

  ci:
    desc: Run init, fmt, and validate (CI)
    cmds:
      - doppler run -- sh -c 'TF_TOKEN_app_terraform_io=${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }} terraform init -backend=false'
      - terraform fmt -check -recursive
      - terraform validate

  test:
    desc: Run init, fmt, and validate
    cmds:
      - doppler run -- sh -c 'TF_TOKEN_app_terraform_io=$TF_TOKEN_APP_TERRAFORM_IO terraform init -backend=false'
      - terraform fmt -check -recursive
      - terraform validate

  plan:
    desc: Format, validate, and plan Terraform changes
    cmds:
      - terraform fmt -check -recursive
      - terraform validate
      - doppler run -- sh -c 'TF_TOKEN_app_terraform_io=$TF_TOKEN_APP_TERRAFORM_IO terraform plan --out=tfplan.out'

  apply:
    desc: Apply Terraform changes with confirmation
    cmds:
      - doppler run -- sh -c 'TF_TOKEN_app_terraform_io=$TF_TOKEN_APP_TERRAFORM_IO terraform apply tfplan.out
      - rm -f tfplan.out
