---
- name: Create RustDesk data directory
  ansible.builtin.file:
    path: "{{ rustdesk_data_path }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  become: true

- name: Install Docker Python SDK
  ansible.builtin.package:
    name: python3-docker
    state: present
  become: true
