---
ollama_version: "0.20.5"
ollama_install_script_url: "https://github.com/ollama/ollama/releases/download/v{{ ollama_version }}/install.sh"
ollama_install_script_checksum: "sha256:25f64b810b947145095956533e1bdf56eacea2673c55a7e586be4515fc882c9f"
ollama_host: "0.0.0.0"
ollama_port: 11434
ollama_expose: false
ollama_num_parallel: 1
ollama_models:
  - gemma4:e2b
  - qwen2.5-coder:7b
open_webui_enabled: false
open_webui_version: "main"
open_webui_port: 3000
open_webui_expose: false
open_webui_watchtower_version: "latest"
ollama_update_script: "https://ollama.com/install.sh"
ollama_update_schedule: "03:00:00"
