---
# handlers file for r8152

- name: Reload udev rules
  ansible.builtin.shell:
    cmd: udevadm control --reload-rules && udevadm trigger
    executable: /bin/bash
  changed_when: true

- name: Update initramfs
  ansible.builtin.shell:
    cmd: update-initramfs -u -k all
    executable: /bin/bash
  changed_when: true
