---
apiVersion: 1

contactPoints:
  - orgId: 1
    name: Pushover
    receivers:
      - uid: pushover-main
        type: pushover
        settings:
          apiToken: $PUSHOVER_APP_TOKEN
          userKey: $PUSHOVER_USER_KEY
          priority: 0
          okPriority: -2
        disableResolveMessage: false
