---
- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ uptime_kuma_base_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  notify: restart uptime-kuma

- name: Start uptime-kuma Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ uptime_kuma_base_path }}"
    state: present
    pull: missing
  when: not ansible_check_mode
