---
- name: Restart Prometheus
  community.docker.docker_container:
    name: prometheus
    state: started
    restart: true
  become: true
  when:
    - not ansible_check_mode
    - not (molecule_testing | default(false))

- name: Restart Grafana
  community.docker.docker_container:
    name: grafana
    state: started
    restart: true
  become: true
  when:
    - not ansible_check_mode
    - not (molecule_testing | default(false))

- name: Restart pve-exporter
  community.docker.docker_container:
    name: pve-exporter
    state: started
    restart: true
  become: true
  when:
    - not ansible_check_mode
    - not (molecule_testing | default(false))
