---
name: Terraform Validation

on:
  push:
    branches: ["*"]
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Create Terraform plugin cache directory
        run: mkdir -p ~/.terraform.d/plugin-cache

      - name: Cache Terraform providers
        uses: actions/cache@v5
        with:
          path: ~/.terraform.d/plugin-cache
          key: >-
            ${{ runner.os }}-terraform-providers-
            ${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-providers-

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }} # doppler github sync
          terraform_wrapper: false
        env:
          TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache

      - name: Terraform Validate
        working-directory: ./terraform
        run: task ci
